function GUI_FREQ_EigCal_Scan_domain_Contour_domain_splitting
% This function is used to split the scan domain and contour domain

global CI
%
% -------------------- s coordinates grids --------------------------------
% For scan domain
CI.EIG.Scan.GRSp        = linspace( CI.EIG.Scan.GRMin,...
                                    CI.EIG.Scan.GRMax,...
                                    CI.EIG.Scan.GRNum);
CI.EIG.Scan.FreqSp      = linspace( CI.EIG.Scan.FreqMin,...
                                    CI.EIG.Scan.FreqMax,...
                                    CI.EIG.Scan.FreqNum);
% -------------------------------------------------------------------------
% For Contour domain
CI.EIG.Cont.GRSp        = linspace( CI.EIG.Scan.GRMin,...
                                    CI.EIG.Scan.GRMax,...
                                 10*CI.EIG.Scan.GRNum);
CI.EIG.Cont.FreqSp      = linspace( CI.EIG.Scan.FreqMin,...
                                    CI.EIG.Scan.FreqMax,...
                                 10*CI.EIG.Scan.FreqNum);
assignin('base','CI',CI);
% -----------------------------end-----------------------------------------
                             